-- =============================================================
-- HERRAMIENTA DE CAPTURA DE DATOS
-- Esquema: bd_origen3
-- Tablas: formulario, seccion, codigo_acceso
-- =============================================================

-- -------------------------------------------------------------
-- Recrear el esquema desde cero
-- -------------------------------------------------------------
DROP SCHEMA IF EXISTS bd_origen3 CASCADE;
CREATE SCHEMA bd_origen3;

-- -------------------------------------------------------------
-- 1. FORMULARIO
-- -------------------------------------------------------------
CREATE TABLE bd_origen3.formulario (
    id_formulario   integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo          VARCHAR(50)  NOT NULL,
    nombre          VARCHAR(255) NOT NULL,
    descripcion     TEXT,
    metadata        JSONB        NOT NULL DEFAULT '{}',

    CONSTRAINT pk_formulario
        PRIMARY KEY (id_formulario),

    CONSTRAINT uq_formulario_codigo
        UNIQUE (codigo)
);

-- -------------------------------------------------------------
-- 2. SECCION
-- -------------------------------------------------------------
CREATE TABLE bd_origen3.seccion (
    id_seccion      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_formulario   integer      NOT NULL,
    codigo          VARCHAR(50)  NOT NULL,
    nombre          VARCHAR(255) NOT NULL,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    en_edicion      BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_seccion
        PRIMARY KEY (id_seccion),

    CONSTRAINT uq_seccion_codigo_formulario
        UNIQUE (codigo, id_formulario),

    CONSTRAINT fk_seccion_formulario
        FOREIGN KEY (id_formulario)
        REFERENCES bd_origen3.formulario (id_formulario)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Índice para buscar rápidamente secciones en edición
CREATE INDEX idx_seccion_en_edicion
    ON bd_origen3.seccion (en_edicion)
    WHERE en_edicion = TRUE;

-- -------------------------------------------------------------
-- 3. CODIGO_ACCESO
-- -------------------------------------------------------------
CREATE TABLE bd_origen3.codigo_acceso (
    id_codigo_acceso   integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo             CHAR(6)      NOT NULL,
    activo             BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_codigo_acceso
        PRIMARY KEY (id_codigo_acceso),

    CONSTRAINT uq_codigo_acceso_codigo
        UNIQUE (codigo),

    CONSTRAINT chk_codigo_solo_digitos
        CHECK (codigo ~ '^[0-9]{6}$')
);
