-- =========================================================
-- Esquema: "bd"
-- =========================================================

DROP SCHEMA IF EXISTS "bd" CASCADE;
CREATE SCHEMA "bd";

-- =========================================================
-- 1 Proyecto
-- =========================================================

CREATE TABLE "bd".proyecto (
  id_proyecto  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       text NOT NULL,
  estado       text NOT NULL DEFAULT 'ACTIVO',
  creado_en    timestamptz NOT NULL DEFAULT now(),
  metadata     jsonb
);

-- =========================================================
-- 2 Encuesta
-- =========================================================

CREATE TABLE "bd".encuesta (
  id_encuesta     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proyecto     integer NOT NULL REFERENCES "bd".proyecto(id_proyecto) ON DELETE CASCADE,
  nombre          text NOT NULL,
  descripcion     text,
  creada_en       timestamptz NOT NULL DEFAULT now(),
  activa          boolean NOT NULL DEFAULT true,
  origen          text NOT NULL DEFAULT 'SIE',
  metadata     jsonb,
  CONSTRAINT uq_encuesta_proyecto_nombre UNIQUE (id_proyecto, nombre)
);

-- =========================================================
-- 3 Encuesta Versión
-- =========================================================

CREATE TABLE "bd".encuesta_version (
  id_encuesta_version  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_encuesta          integer NOT NULL REFERENCES "bd".encuesta(id_encuesta) ON DELETE CASCADE,
  alias                varchar(100),
  version              varchar(50) NOT NULL,
  etiqueta             text,
  estado               text NOT NULL DEFAULT 'BORRADOR',
  vigente_desde        date,
  vigente_hasta        date,
  creada_en            timestamptz NOT NULL DEFAULT now(),
  metadata             jsonb,
  CONSTRAINT uq_version_encuesta_version UNIQUE (id_encuesta, version),
  CONSTRAINT ck_version_vigencia CHECK (
    vigente_desde IS NULL OR vigente_hasta IS NULL OR vigente_desde <= vigente_hasta
  )
);

-- =========================================================
-- 4 Sección
-- =========================================================

CREATE TABLE "bd".seccion (
  id_seccion           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_encuesta_version  integer NOT NULL REFERENCES "bd".encuesta_version(id_encuesta_version) ON DELETE CASCADE,
  orden                integer NOT NULL,
  titulo               text NOT NULL,
  metadata     jsonb,
  CONSTRAINT ck_seccion_orden_pos CHECK (orden > 0)
);

-- =========================================================
-- 5 Página
-- =========================================================

CREATE TABLE "bd".pagina (
  id_pagina   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_seccion  integer NOT NULL REFERENCES "bd".seccion(id_seccion) ON DELETE CASCADE,
  orden       integer NOT NULL,
  titulo      text,
  metadata     jsonb,
  CONSTRAINT ck_pagina_orden_pos CHECK (orden > 0)
);

-- =========================================================
-- 6 Tipo Pregunta
-- =========================================================

CREATE TABLE "bd".tipo_pregunta (
  id_tipo_pregunta  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo            text NOT NULL UNIQUE,
  descripcion       text,
  usa_lista         boolean NOT NULL DEFAULT false
);

-- =========================================================
-- 7 Tipo Lista
-- =========================================================

CREATE TABLE "bd".tipo_lista (
  id_tipo_lista  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre         varchar(50) NOT NULL UNIQUE
);

-- =========================================================
-- 8 Lista
-- =========================================================

CREATE TABLE "bd".lista (
  id_lista            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_encuesta_version integer REFERENCES "bd".encuesta_version(id_encuesta_version) ON DELETE CASCADE,
  nombre              text,
  descripcion         text,
  id_tipo_lista       integer REFERENCES "bd".tipo_lista(id_tipo_lista),
  id_lista_padre      integer REFERENCES "bd".lista(id_lista) ON DELETE SET NULL,
  creada_en           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_lista_version_nombre UNIQUE (id_encuesta_version, nombre)
);

-- =========================================================
-- 9 Lista Item
-- =========================================================

CREATE TABLE "bd".lista_item (
  id_lista_item  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_lista       integer NOT NULL REFERENCES "bd".lista(id_lista) ON DELETE CASCADE,
  orden          integer NOT NULL,
  valor          text NOT NULL,
  etiqueta       text NOT NULL,
  valor_filtro   text,
  activo         boolean NOT NULL DEFAULT true,
  CONSTRAINT ck_lista_item_orden_pos CHECK (orden > 0)
);

CREATE UNIQUE INDEX uq_lista_item_valor_filtro
  ON "bd".lista_item(id_lista, valor, COALESCE(valor_filtro, ''));

-- =========================================================
-- 10 Grupo
-- =========================================================

CREATE TABLE "bd".grupo (
  id_grupo             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_encuesta_version  integer NOT NULL REFERENCES "bd".encuesta_version(id_encuesta_version) ON DELETE CASCADE,
  id_grupo_padre       integer REFERENCES "bd".grupo(id_grupo) ON DELETE SET NULL,
  nombre_grupo         text,
  etiqueta             text NOT NULL,
  repeticion           text,
  orden                integer NOT NULL,
  metadata             jsonb,
  CONSTRAINT ck_grupo_orden_pos CHECK (orden > 0)
);

-- =========================================================
-- 11 Pregunta
-- =========================================================

CREATE TABLE "bd".pregunta (
  id_pregunta       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pagina         integer NOT NULL REFERENCES "bd".pagina(id_pagina) ON DELETE CASCADE,
  id_tipo_pregunta  integer NOT NULL REFERENCES "bd".tipo_pregunta(id_tipo_pregunta),
  id_lista          integer REFERENCES "bd".lista(id_lista),
  id_grupo          integer REFERENCES "bd".grupo(id_grupo) ON DELETE SET NULL,
  nombre_grupo      text,
  orden             integer NOT NULL,
  codigo            text,
  texto             text NOT NULL,
  requerida         boolean NOT NULL DEFAULT false,
  requerida_mensaje text,
  ayuda             text,
  filtro_lista      text,
  metadata          jsonb,
  CONSTRAINT ck_pregunta_orden_pos CHECK (orden > 0),
  CONSTRAINT uq_pregunta_pagina_codigo UNIQUE (id_pagina, codigo)
);

-- =========================================================
-- 12 Tipo Expresión
-- =========================================================

CREATE TABLE "bd".tipo_expresion (
  id_tipo_expresion  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo             text NOT NULL UNIQUE,
  descripcion        text
);

-- =========================================================
-- 13 Expresión
-- =========================================================

CREATE TABLE "bd".expresion (
  id_expresion       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pregunta        integer NOT NULL REFERENCES "bd".pregunta(id_pregunta) ON DELETE CASCADE,
  id_tipo_expresion  integer NOT NULL REFERENCES "bd".tipo_expresion(id_tipo_expresion),
  orden              integer NOT NULL DEFAULT 1,
  regla              text NOT NULL,
  tipo               text,
  mensaje            text,
  activa             boolean NOT NULL DEFAULT true,
  parametros_json    jsonb,
  creada_en          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_expresion_orden_pos CHECK (orden > 0),
  CONSTRAINT uq_expresion_pregunta_tipo_orden UNIQUE (id_pregunta, id_tipo_expresion, orden)
);

-- =========================================================
-- 14 Pregunta Grupo
-- =========================================================

CREATE TABLE IF NOT EXISTS "bd".pregunta_grupo (
    id_pregunta_grupo  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_grupo           integer NOT NULL,
    id_pregunta        integer NOT NULL,
    pos_fila           integer,
    pos_columna        integer,
    es_autonumerico    boolean DEFAULT false,
    etiqueta_fila      text,
    etiqueta_columna   text,
    alias_fila         text,
    alias_columna      text,
    
    -- FOREIGN KEYS (relaciones faltantes)
    CONSTRAINT fk_pregunta_grupo_grupo 
        FOREIGN KEY (id_grupo) 
        REFERENCES "bd".grupo(id_grupo) 
        ON DELETE CASCADE,
    
    CONSTRAINT fk_pregunta_grupo_pregunta 
        FOREIGN KEY (id_pregunta) 
        REFERENCES "bd".pregunta(id_pregunta) 
        ON DELETE CASCADE,
    
    -- Unique constraint para evitar duplicados
    CONSTRAINT uq_pregunta_grupo_unique 
        UNIQUE (id_grupo, id_pregunta)
);

-- =========================================================
-- 15 Índices recomendados
-- =========================================================

CREATE UNIQUE INDEX IF NOT EXISTS ix_encuesta_version_alias 
  ON "bd".encuesta_version(alias, version) 
  WHERE alias IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_encuesta_proyecto   
  ON "bd".encuesta(id_proyecto);

CREATE INDEX IF NOT EXISTS ix_encuesta_origen
  ON "bd".encuesta(origen);

CREATE INDEX IF NOT EXISTS ix_version_encuesta    
  ON "bd".encuesta_version(id_encuesta);

CREATE INDEX IF NOT EXISTS ix_seccion_version     
  ON "bd".seccion(id_encuesta_version);

CREATE INDEX IF NOT EXISTS ix_pagina_seccion      
  ON "bd".pagina(id_seccion);

CREATE INDEX IF NOT EXISTS ix_pregunta_pagina     
  ON "bd".pregunta(id_pagina);

CREATE INDEX IF NOT EXISTS ix_pregunta_pagina_orden
  ON "bd".pregunta(id_pagina, orden);

CREATE INDEX IF NOT EXISTS ix_pregunta_tipo       
  ON "bd".pregunta(id_tipo_pregunta);

CREATE INDEX IF NOT EXISTS ix_pregunta_lista      
  ON "bd".pregunta(id_lista);

CREATE INDEX IF NOT EXISTS ix_lista_tipo_lista    
  ON "bd".lista(id_tipo_lista);

CREATE INDEX IF NOT EXISTS ix_lista_version       
  ON "bd".lista(id_encuesta_version);

CREATE INDEX IF NOT EXISTS ix_lista_item_lista    
  ON "bd".lista_item(id_lista);

CREATE INDEX IF NOT EXISTS ix_expresion_pregunta  
  ON "bd".expresion(id_pregunta);

CREATE INDEX IF NOT EXISTS ix_expresion_tipo      
  ON "bd".expresion(id_tipo_expresion);

CREATE INDEX IF NOT EXISTS ix_grupo_version       
  ON "bd".grupo(id_encuesta_version);

CREATE INDEX IF NOT EXISTS ix_grupo_version_orden
  ON "bd".grupo(id_encuesta_version, orden);

CREATE INDEX IF NOT EXISTS ix_grupo_padre         
  ON "bd".grupo(id_grupo_padre);

CREATE INDEX IF NOT EXISTS ix_pregunta_grupo      
  ON "bd".pregunta(id_grupo);

CREATE INDEX IF NOT EXISTS ix_pregunta_grupo_grupo 
    ON "bd".pregunta_grupo(id_grupo);

CREATE INDEX IF NOT EXISTS ix_pregunta_grupo_pregunta 
    ON "bd".pregunta_grupo(id_pregunta);

--------------------------------------------------------------
-- PARA INSTRUMENTO INGRESO DICCIONARIO ENCUESTAS
--------------------------------------------------------------

CREATE TABLE "bd".tmp_diccionario (
	id_diccionario integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	data jsonb NOT null,
	CONSTRAINT id_diccionario PRIMARY KEY (id_diccionario)
);



